---
 environment: development
 address: 127.0.0.1
 user: thin
 group: thin
 port: 4567
 pid: ./thin.pid
 rackup: ./config.ru
 log: ./thin.log
 max_conns: 1024
 timeout: 30
 max_persistent_conns: 512
 daemonize: false
 threaded: true