---
 environment: development
 address: 127.0.0.1
 user: gleichsnerd
 group: staff
 port: 8282
 pid: ./thin.pid
 rackup: ./config.ru
 log: ./thin.log
 max_conns: 1024
 timeout: 480
 max_persistent_conns: 512
 daemonize: false
 threaded: true